PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX schema: <http://schema.org/>

# Query to get SHACL validation violations that are not in the ignored properties list.
SELECT ?node ?path ?message
WHERE {
    ?report a sh:ValidationReport ;
        sh:result ?result .
    ?result sh:focusNode ?node ;
            sh:resultPath ?path ;
            sh:resultMessage ?message .

    # Filter out ignored properties (partial examples may not have these).
    FILTER (?path NOT IN (
         # CreativeWork:
         schema:name,
         schema:creator,
         schema:associatedMedia,
         schema:isPartOf,

         # MediaObject:
         schema:license,
         schema:contentUrl,
         schema:thumbnailUrl
     )
    )
}
